version: '3'
services:
  server:
    build: server
    stdin_open: true
    tty: true
    env_file:
      - ./.env
    ports:
      - "3001:3001"
    volumes:
      - ./server:/server
  ui:
    build: ui
    stdin_open: true
    tty: true
    ports:
      - "3000:3000"
    volumes:
      - ./ui:/ui
  admin:
    build: admin
    stdin_open: true
    tty: true
    ports:
      - "3002:3002"
    volumes:
      - ./admin:/admin
  setup:
    build: setup
    stdin_open: true
    tty: true
    env_file:
      - ./.env
    volumes:
      - ./setup:/setup

