version: '3'
services:

  # For testing purpose
  datadog_agent:
    image: datadog/agent
    env_file:
      - ./.env
    ports:
      - "8126:8126"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup:/host/sys/fs/cgroup:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro

  jira-app:
    build: jira-app
    stdin_open: true
    tty: true
    env_file:
      - ./.env
    ports:
      - "3020:3000"
    volumes:
      - ./jira-app:/jira-app

  jira-proxy:
    build: jira-proxy
    stdin_open: true
    tty: true
    env_file:
      - ./.env
    ports:
      - "3030:3000"
    volumes:
      - ./jira-proxy:/jira-proxy

