version: '3'
services:
    crystal-api:
        build:
            context: crystal-api
            target: build
        environment:
            BIND: 0.0.0.0
            PORT: 8080
        ports:
            - '8080:8080'
