version: '3'
services:
    crystal-api:
        build:
            context: crystal-api
            target: build
        environment:
            BIND: 0.0.0.0
            PORT: 8080
        ports:
            - '8080:8080'
    datadog-app:
        build: datadog-app
        command: yarn start
        environment:
            REACT_APP_API_URL: http://localhost:8080
        ports:
            - '3000:3000'
    setup:
        build: setup
        command: yarn start
        env_file: ./.env
