version: '3'
services:
  crystal-api:
    build: crystal-api
    stdin_open: true
    tty: true
    environment:
      BIND: "0.0.0.0"
      PORT: "8080"
    ports:
      - "8080:8080"
    volumes:
      - ./crystal-api:/api

