version: '3'
services:
    app:
        command: yarn start
        build: datadog-app
        environment:
            REACT_APP_API_URL: http://localhost:3001
            REACT_APP_PROXY_URL: http://localhost:5000
        ports:
            - '3002:3000'

    api:
        command: node index.js
        build: slice-life-pizzeria
        ports:
            - '3001:3000'

    proxy:
        build: proxy
        command: flask run --port=5000 --host=0.0.0.0
        environment:
            API_URL: http://api:3000/api
        ports:
            - '5000:5000'

    setup:
        command: yarn start
        build: setup
        env_file:
            - ./.env
