version: '3'
services:

  app:
    build: datadog-app 
    stdin_open: true
    tty: true
    environment:
      REACT_APP_API_URL: http://localhost:3001
      REACT_APP_PROXY_URL: http://api:5000
    ports:
      - '3002:3000'
    volumes:
      - ./datadog-app:/datadog-app

  api:
    build: slice-life-pizzeria
    stdin_open: true
    tty: true
    ports:
      - '3001:3000'
    volumes:
      - ./slice-life-pizzeria:/api

  proxy:
    build: proxy
    stdin_open: true
    tty: true
    ports:
      - '5000:5000'
    volumes:
      - ./proxy:/proxy

