name: Continuous Integration

on:
    - push

jobs:
    ci:
        runs-on: ubuntu-latest
        env:
            CI: true

        steps:
            - name: checkout
              uses: actions/checkout@v2
            - name: install node
              uses: actions/setup-node@v1
              with:
                  node-version: 16.3.0
            - name: install
              run: yarn
            - name: lint
              run: yarn lint
            - name: build
              run: yarn build
            - name: test
              run: yarn test
