name: Continuous Integration

on:
    - push

jobs:
    ci:
        runs-on: ubuntu-latest
        env:
            CI: true

        steps:
            - name: checkout
              uses: actions/checkout@v2
            - name: install node
              uses: actions/setup-node@v2
              with:
                  cache: yarn
                  node-version-file: .node-version
            - name: install
              run: yarn
            - name: lint
              run: yarn lint
            - name: build
              run: yarn build
            - name: test
              run: yarn test
