name: Publish changed packages

on:
    push:
        branches:
            - master

concurrency:
    group: ${{ github.ref }}-publish
    cancel-in-progress: true

jobs:
    publish:
        runs-on: ubuntu-latest
        env:
            NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        steps:
            - name: Checkout repo
              uses: actions/checkout@v3

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version-file: '.node-version'
                  cache: 'yarn'
                  registry-url: 'https://registry.npmjs.org'
                  scope: '@datadog'

            - name: Install dependencies
              run: yarn --prefer-offline

            - name: Build packages
              run: yarn build

            - name: Create release Pull Request or publish to npm
              id: changesets
              uses: changesets/action@v1
              with:
                  # `commit` sets the commit message.
                  # Using `[skip canary]` should force `auto` to ignore these PRs/publishes.
                  commit: Version Packages [skip canary]
                  publish: yarn release:packages
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
