name: Publish canary package
on:
    push:
        branches-ignore:
            - 'gh-pages'
            - master

jobs:
    publish:
        runs-on: ubuntu-latest
        if: "!contains(github.event.head_commit.message, 'skip canary')"
        steps:
            - uses: actions/checkout@v2
            - name: Prepare repository
              run: git fetch --unshallow --tags
            - uses: actions/setup-node@v1
              with:
                  node-version: 16.3.0
                  registry-url: 'https://registry.npmjs.org'
                  scope: '@datadog'
            - run: yarn
            - name: Add auth credentials for publishing
              run: npm config set //registry.npmjs.org/:_authToken=${NPM_TOKEN}
              env:
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
            - run: yarn release:canary
              env:
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: Get Pull Request Number
              id: pr
              run: echo "::set-output name=number::$(gh pr view --json number -q .number || echo "")"
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: Show diff
              run: git diff --name-only -- 'packages/*/package.json'

            - name: Get comment information
              id: comment-information
              uses: actions/github-script@v5.1.0
              with:
                github-token: ${{ secrets.GITHUB_TOKEN }}
                script: |
                  const fs = require("fs");
                  const os = require("os");

                  const packageJSONFilenamesOutput = await exec.getExecOutput("git diff --name-only -- 'packages/*/package.json'");
                  const packageJSONFilenames = packageJSONFilenamesOutput.stdout.split(os.EOL);
                  console.log({packageJSONFilenames});

                  let body = [];
                  for (const packageJSONFilename of packageJSONFilenames) {
                      const packageJSON = require(packageJSONFilename);
                      body.push("yarn add " + packageJSON.name + "@" + packageJSON.version);
                  }
                  console.log({ helloOutput, body });

                  core.setOutput("body", body.join(os.EOL));

            - name: Debug outputs
              run: |
                echo PR Number ${{ steps.pr.outputs.number }}
                echo Body ${{ steps.comment-information.outputs.body }}
                echo Hello ${{ steps.comment-information.outputs.hello }}

            - name: Comment PR
              uses: peter-evans/create-or-update-comment@v1
              with:
                issue-number: ${{ steps.pr.outputs.number }}
                body: ${{ steps.comment-information.outputs.body }}
