name: Publish canary package
on:
    push:
        branches-ignore:
            - 'gh-pages'
            - master

jobs:
    publish:
        runs-on: ubuntu-latest
        if: "!contains(github.event.head_commit.message, 'skip canary')"
        steps:
            - uses: actions/checkout@v2
            - name: Prepare repository
              run: git fetch --unshallow --tags
            - uses: actions/setup-node@v1
              with:
                  node-version: 16.3.0
                  registry-url: 'https://registry.npmjs.org'
                  scope: '@datadog'
            - run: yarn
            - run: yarn build
            - name: Add auth credentials for publishing
              run: npm config set //registry.npmjs.org/:_authToken=${NPM_TOKEN}
              env:
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
            - run: yarn release:canary
              env:
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: Format comment 
              id: comment
              run: |
                output=$(git tag --contains HEAD --list --format='yarn add %(refname:strip=2)')
                echo "::set-output name=result::${output}"

            - name: Comment PR
              uses: peter-evans/create-or-update-comment@v1
              with:
                issue-number: ${{ github.event.pull_request.number }}
                body: ${{ steps.comment.outputs.result }}
