name: Publish API documentation

on:
    push:
        branches:
            - master

concurrency:
    group: ${{ github.ref }}-api-docs
    cancel-in-progress: true

jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v3

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version-file: '.node-version'
                  cache: 'yarn'

            - name: Install dependencies
              run: yarn install --prefer-offline

            - name: Build all packages
              run: yarn build

            - name: Build API documentation
              run: yarn docs

            - name: Deploy to GitHub Pages
              uses: JamesIves/github-pages-deploy-action@v4.2.2
              with:
                  # The branch the action should deploy to.
                  branch: gh-pages
                  # The directory the action should deploy.
                  folder: docs/API/packages
                  git-config-name: github-actions[bot]
                  git-config-email: github-actions[bot]@users.noreply.github.com
